services:
  postgres:
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      - POSTGRES_USER=reffectmenju
      - POSTGRES_PASSWORD=reffectwhat
    ports:
      - '5432:5432'
    volumes:
      - menju_postgres_data:/var/lib/postgresql/data

volumes:
  menju_postgres_data:
